-- DATA INTEGRITY & REPAIR SCRIPT
-- Phase 4: Final Polish

-- 1. Populating Client Logos (The "Marquee" List)
-- Ensuring exactly 24 logos as per brief (using placeholders as exact list is generic here)
CREATE TABLE IF NOT EXISTS client_logos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name TEXT NOT NULL,
    logo_url TEXT,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Fix: The legacy table might have NOT NULL on logo_url, but our frontend supports text-only.
-- Relaxing the constraint to match frontend logic.
DO $$ 
BEGIN 
    ALTER TABLE client_logos ALTER COLUMN logo_url DROP NOT NULL; 
EXCEPTION 
    WHEN OTHERS THEN NULL; -- Ignore if it fails
END $$;

-- Clear existing to ensure clean slate (or use upsert if preferred, but for a list clean is typically safer for "reset" scripts)
DELETE FROM client_logos;

INSERT INTO client_logos (client_name, display_order) VALUES
('TechCorp Global', 1), ('FinServe Intl', 2), ('HealthPlus', 3), ('RetailGiant', 4),
('AutoMotive X', 5), ('EduLearn Systems', 6), ('ConstructCo', 7), ('EnergyFlow', 8),
('LogiTrans', 9), ('MediaStream', 10), ('AgriTech', 11), ('CyberSecure', 12),
('CloudNative', 13), ('DataDynamo', 14), ('AI Frontiers', 15), ('BlockChain Viz', 16),
('GreenEnergy', 17), ('UrbanSpaces', 18), ('AeroSpace One', 19), ('Oceanic Shipping', 20),
('TeleConnect', 21), ('FoodWorks', 22), ('BioLife', 23), ('FutureFinance', 24);

-- 2. Fixing Framework Icons (Ensuring valid Lucide names)
UPDATE frameworks SET icon_name = 'Layers' WHERE icon_name IS NULL OR icon_name = '';
UPDATE frameworks SET icon_name = 'Target' WHERE slug = 'gtm-velocity';
UPDATE frameworks SET icon_name = 'Users' WHERE slug = 'customer-centricity';
UPDATE frameworks SET icon_name = 'BarChart3' WHERE slug = 'revenue-architecture';
UPDATE frameworks SET icon_name = 'Shield' WHERE slug = 'retention-safeguard';
UPDATE frameworks SET icon_name = 'Zap' WHERE slug = 'digital-transformation';
UPDATE frameworks SET icon_name = 'Globe' WHERE slug = 'global-expansion';
UPDATE frameworks SET icon_name = 'Briefcase' WHERE slug = 'sales-enablement';
UPDATE frameworks SET icon_name = 'Lightbulb' WHERE slug = 'product-innovation';
UPDATE frameworks SET icon_name = 'TrendingUp' WHERE slug = 'market-penetration';
UPDATE frameworks SET icon_name = 'Award' WHERE slug = 'brand-equity';

-- 3. Fixing Industry Icons
UPDATE industries SET icon_name = 'Building2' WHERE icon_name IS NULL OR icon_name = '';
UPDATE industries SET icon_name = 'ShoppingBag' WHERE slug = 'retail';
UPDATE industries SET icon_name = 'Stethoscope' WHERE slug = 'healthcare';
UPDATE industries SET icon_name = 'Landmark' WHERE slug = 'bfsi';
UPDATE industries SET icon_name = 'Factory' WHERE slug = 'manufacturing';
UPDATE industries SET icon_name = 'Monitor' WHERE slug = 'technology';

-- 4. Rich Text Formatting Fixes (Example: Inserting newlines for lists)
-- Ensuring "Challenges" lists in industries are properly formatted if they were raw strings
-- (Note: This assumes specific_data -> 'list' is a JSONB array. If it was a string, we'd fix it here.
-- Since our code handles array mapping, we ensure the DATA is indeed an array)

-- Example: Fix Retail Challenges if they were generic
UPDATE sections_industries
SET specific_data = jsonb_set(
    specific_data,
    '{list}',
    '["Fragmented Customer Data across channels", "Legacy Supply Chain constraints", "Declining In-Store Footfall vs Digital", "Personalization at Scale failures"]'
)
WHERE page_slug = 'retail' AND section_key = 'challenges';

-- Example: Fix Technology Challenges
UPDATE sections_industries
SET specific_data = jsonb_set(
    specific_data,
    '{list}',
    '["Rapid Feature Commoditization", "High CAC / Low LTV ratios", "Churn in SaaS subscription models", "Enterprise Sales Cycle Friction"]'
)
WHERE page_slug = 'technology' AND section_key = 'challenges';

-- 5. Fix Service Description Formatting (Adding paragraphs via \n\n)
UPDATE sections_services
SET specific_data = jsonb_set(
    specific_data,
    '{steps}',
    '[
        {"title": "Audit & Discovery", "desc": "We deep dive into your current state.\\n\\nIdentifying gaps in process, people, and platforms to build a baseline."},
        {"title": "Strategy Design", "desc": "Co-creating the future state roadmap.\\n\\nWe align stakeholders around a shared vision and measurable KPIs."},
        {"title": "Execution & Enablement", "desc": "Rolling out the change.\\n\\nWe stand up the teams, tools, and training needed to sustain growth."}
    ]'
)
WHERE section_key = 'approach_steps';
