-- Update Services / Program Pages Data
-- Source: Section 4 of website-design-brief.md

INSERT INTO public.sections_services (page_slug, display_order, section_key, title, subtitle, bg_theme, specific_data, primary_cta_text, admin_instruction) VALUES
-- 1. Pre-Sales Transformation
('pre-sales', 1, 'hero', 'Build a High-Accuracy Go-To-Market Foundation', 'Align your brand promise, personas, messaging and expectation frameworks to create a Go-To-Market engine that consistently brings the right customers into your pipeline.', 'navy', '{"badge": "Pre-Sales Transformation"}', 'Book a GTM Strategy Review', 'Hero section for Pre-Sales page'),
('pre-sales', 2, 'problem_block', 'Why Pre-Sales Fails', 'Most Pre-Sales systems fail not because teams lack leads, but because they lack clarity and alignment.', 'light', '{"list": ["Clarity of promise (Brand Promise not grounded in reality)", "Clarity of persona (demographic personas instead of behavioral ones)", "Clarity of pitch (feature-first, expectation-last)", "Alignment across functions (Marketing → Sales → CS misaligned)", "Expectation Match (customer expectations ≠ organizational delivery)"]}', NULL, 'Problem statement block'),
('pre-sales', 3, 'approach_steps', 'Our Approach: Anchored in Frameworks', 'We use a systematic approach anchored 100% in your frameworks.', 'gray', '{"steps": [{"title": "CX Maturity Framework Diagnostic", "desc": "Baselines how well the organization articulates, communicates and delivers its Brand Promise across journeys."}, {"title": "Expectation Management Framework (EMM)", "desc": "Maps customer expectations against organizational delivery to identify high-impact GTM interventions."}, {"title": "Persona–Product–Pitch Playbook", "desc": "Defines who we sell to, what they expect, and how we pitch value using behavioral personas."}, {"title": "Peak Purpose + Leadership Alignment", "desc": "Vision → Mission → Values → Goals → OKRs workshop ensuring leaders share a north star."}, {"title": "Discovery & Proposal Storylines", "desc": "A repeatable GTM structure driven by expectation-based pitching, not features."}]}', NULL, 'Methodology/Approach steps'),
('pre-sales', 4, 'outcomes_grid', 'Measurable Impact', 'Outcomes driven by GTM transformation.', 'light', '{"stats": [{"label": "Marketing/BD Conversion", "value": "+15-25%"}, {"label": "Retention", "value": "+12-25%"}, {"label": "Funnel Predictability", "value": "+20-30%"}, {"label": "Decision Speed", "value": "+25%"}, {"label": "Handoff Friction", "value": "Lower"}]}', 'Explore All GTM Case Studies', 'Key impact statistics'),

-- 2. Sales Velocity Acceleration
('sales-velocity', 1, 'hero', 'Accelerate Sales Velocity With Value-Led Selling', 'Equip teams with the Value Realization narratives, expectation-aligned pitching, and sales governance required to shorten cycles and improve win rates.', 'navy', '{"badge": "Sales Velocity Acceleration"}', 'Book a Sales Velocity Audit', 'Hero section for Sales Velocity page'),
('sales-velocity', 2, 'problem_block', 'When Sales Velocity Suffers', 'Sales velocity suffers when discovery is shallow and expectations are misaligned.', 'light', '{"list": ["Discovery is shallow", "Expectations are not aligned early", "Every seller has their own pitch", "Value is not tied to customer KPIs", "Forecasting lacks consistency", "Sales → CS handoff is broken"]}', NULL, 'Problem statement block'),
('sales-velocity', 3, 'approach_steps', 'Our Approach: Value & Governance', 'Systematic intervention for speed, quality, and predictability.', 'gray', '{"steps": [{"title": "Persona–Product–Pitch (PPP) Playbook", "desc": "Moves sellers from \"feature demonstration\" to \"expectation alignment\"."}, {"title": "Value Realization Map (VRM™)", "desc": "Links capabilities to customer success metrics, business KPIs, and economics."}, {"title": "Expectation Management Framework", "desc": "Anticipates friction points + objections; improves proposal quality."}, {"title": "Sales Governance Rhythm", "desc": "Review templates, scorecards, forecast accuracy structures."}, {"title": "Sales → CS Alignment", "desc": "Integrated lifecycle flow using Customer Lifecycle Heatmap."}]}', NULL, 'Methodology/Approach steps'),
('sales-velocity', 4, 'outcomes_grid', 'Measurable Impact', 'Outcomes driven by sales transformation.', 'light', '{"stats": [{"label": "Sales Velocity", "value": "2x–5x"}, {"label": "Conversion Improvement", "value": "+15–30%"}, {"label": "Forecast Accuracy", "value": "+15–32%"}, {"label": "Close Rate", "value": "Higher"}]}', 'View Sales Impact Stories', 'Key impact statistics'),

-- 3. Customer Success & Post-Sales Transformation
('customer-success', 1, 'hero', 'Transform Customer Success Into a Revenue Engine', 'Design segmentation, journeys, value realization, health scoring and advocacy motions that increase retention, expansion and Net Revenue Retention (NRR).', 'navy', '{"badge": "Customer Success Transformation"}', 'Take the CS Maturity Assessment', 'Hero section for CS page'),
('customer-success', 2, 'problem_block', 'The CS Struggle', 'Organizations struggle when CS is trapped in reactive modes.', 'light', '{"list": ["CS is trapped in ticket-solving mode", "No common lifecycle view exists", "Renewals are last-minute", "Value is not captured or communicated", "No advocacy or co-creation program exists", "Health score models are inaccurate"]}', NULL, 'Problem statement block'),
('customer-success', 3, 'approach_steps', 'Our Approach: The Post-Sales System', 'Operationalizing success for revenue and advocacy.', 'gray', '{"steps": [{"title": "Customer Success Maturity Model (31Q)", "desc": "Your canonical, 10-domain CS diagnostic."}, {"title": "Customer Lifecycle Heatmap", "desc": "Maps signals of adoption, usage, value, risk & expansion."}, {"title": "V.I.C.T.O.R.Y™ Framework", "desc": "Your proprietary 7-stage CS-to-Revenue framework."}, {"title": "Value Realization Map (VRM)", "desc": "Connects customer outcomes to your economic metrics."}, {"title": "9Ps Advocacy Framework", "desc": "Turns customers into co-creators, storytellers, advocates."}, {"title": "CX ROI Calculator", "desc": "Financial modeling of NPS → economics."}]}', NULL, 'Methodology/Approach steps'),
('customer-success', 4, 'outcomes_grid', 'Measurable Impact', 'Outcomes driven by CS transformation.', 'light', '{"stats": [{"label": "Retention", "value": "+12–25%"}, {"label": "NRR", "value": "+10–25%"}, {"label": "Churn Reduction", "value": "20–35%"}, {"label": "Expansion", "value": "+15–30%"}, {"label": "Advocacy", "value": "2–3x"}, {"label": "Platform Adoption", "value": "+23–28%"}]}', 'Explore Customer Success Case Studies', 'Key impact statistics'),

-- 4. Digital & AI Enablement
('digital-ai', 1, 'hero', 'Digitize Journeys. Unify Data. Amplify Impact.', 'Design digital journeys, feedback loops, AI automation, and Customer 360 systems that improve decision-making, reduce effort, and increase revenue outcomes.', 'navy', '{"badge": "Digital & AI Enablement"}', 'Book a Digital Readiness Review', 'Hero section for Digital AI page'),
('digital-ai', 2, 'problem_block', 'Why Digital Efforts Fail', 'Common pitfalls in digital transformation and tooling.', 'light', '{"list": ["Tools are purchased without value definition", "Data lives in silos (CRM, CS platform, NPS, tickets)", "Customer insights aren’t turned into actions", "AI is superficial, not embedded in journeys", "CX & CS tooling has no ROI measurement"]}', NULL, 'Problem statement block'),
('digital-ai', 3, 'approach_steps', 'Our Approach: Digital System', 'Unifying data and experience through actionable intelligence.', 'gray', '{"steps": [{"title": "Customer 360", "desc": "Unifies policy, claims, complaints, sentiment, digital interactions, adoption."}, {"title": "Journey Digitization", "desc": "Mapping quote, buy, service, renew, claim journeys."}, {"title": "Feedback Loop Entrenchment", "desc": "Multi-source feedback (NPS, CSAT, CES, VoC) converted into action."}, {"title": "AI Enablement & Automation", "desc": "Predictive churn, propensity to upgrade, sentiment classification, self-service redesign."}, {"title": "Platform ROI Measurement", "desc": "Using VRM + CX ROI Calculator."}]}', NULL, 'Methodology/Approach steps'),
('digital-ai', 4, 'outcomes_grid', 'Measurable Impact', 'Outcomes driven by digital enablement.', 'light', '{"stats": [{"label": "Platform Adoption", "value": "+23–28%"}, {"label": "Platform ROI", "value": "+12–18%"}, {"label": "Insight-to-Action", "value": "+25–30%"}, {"label": "Cycle Times", "value": "Faster"}]}', 'View Digital Impact Stories', 'Key impact statistics'),

-- 5. Culture Transformation
('culture-transformation', 1, 'hero', 'Build a Humanized, Aligned, Nimble & Data-Backed Culture', 'Translate core values into daily behaviors, performance systems, rituals and decisions that sustain customer-led growth.', 'navy', '{"badge": "Culture Transformation"}', 'Book a Culture Maturity Conversation', 'Hero section for Culture page'),
('culture-transformation', 2, 'problem_block', 'Why Culture Breaks', 'Barriers to a high-performance, customer-centric culture.', 'light', '{"list": ["Values remain posters", "Leadership is not aligned", "People don’t share a unified purpose", "Hiring, onboarding, performance don’t reflect values", "eNPS is low", "Attrition is high", "Internal collaboration slows initiatives"]}', NULL, 'Problem statement block'),
('culture-transformation', 3, 'approach_steps', 'Our Approach: HAND System', 'Making culture measurable and actionable.', 'gray', '{"steps": [{"title": "Culture Maturity Assessment™", "desc": "Baseline collaboration, accountability, customer-orientation, agility."}, {"title": "H.A.N.D™ Framework", "desc": "Humanized, Aligned, Nimble, Data-backed methodology."}, {"title": "Values Actualization Workshops", "desc": "Connects values to meaning and behaviors."}, {"title": "Hiring & Performance Alignment", "desc": "Role scorecards aligned to values."}, {"title": "Leadership Rituals", "desc": "Town halls, storytelling, and communication alignment."}]}', NULL, 'Methodology/Approach steps'),
('culture-transformation', 4, 'outcomes_grid', 'Measurable Impact', 'Outcomes driven by culture transformation.', 'light', '{"stats": [{"label": "eNPS", "value": "+10–15pp"}, {"label": "Early Attrition", "value": "Reduced"}, {"label": "Collaboration", "value": "Improved"}, {"label": "Innovation Speed", "value": "Increased"}, {"label": "Response Time", "value": "Faster"}]}', 'Explore Culture Transformation Work', 'Key impact statistics')

ON CONFLICT (page_slug, section_key) DO UPDATE SET
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  bg_theme = EXCLUDED.bg_theme,
  specific_data = EXCLUDED.specific_data,
  primary_cta_text = EXCLUDED.primary_cta_text,
  admin_instruction = EXCLUDED.admin_instruction;
